type MatchClosed @entity(immutable: true) {
  id: Bytes!
  matchId: BigInt! # uint256
  winner: Bytes! # address
  reward: BigInt! # uint256
  platformFee: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type MatchCreated @entity(immutable: true) {
  id: Bytes!
  matchId: BigInt! # uint256
  name: String! # string
  stake: BigInt! # uint256
  durationDays: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type PlayerJoined @entity(immutable: true) {
  id: Bytes!
  matchId: BigInt! # uint256
  player: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}
